baseURL: https://ThanhCuong1807.github.io/Blog/
languageCode: en-us
build:
  writeStats: true
title: aafu theme
# Uncomment below to use aafu as hugo theme. See instructions in README.md
theme: aafu

params:
  author: Darshan Baral
  description: Website title
  copyright: >-
    powered by [hugo](https://gohugo.io/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false  

  profile:
    name: "Nguyễn Lê Thanh Cường"
    tagline: "cybersecurity programmer"
    location: ""
    photo: profile1.jpg
  social:
    title: Links
    list:
      - icon: fab fa-facebook-f
        url: "https://www.facebook.com/nguyen.cuong.968814"
        title: Facebook
      - icon: fab fa-github
        url: "https://github.com/ThanhCuong1807/Blog"
        title: GitHub
      - icon: fab fa-tiktok
        url: "https://www.tiktok.com/@nguyencuong1807"
        title: Tiktok


  showInAccordion:
    - item: aboutme
      expand: true

    - item: education
  
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: Giới thiệu bản thân
    icon: fas fa-user
    description:  |
                  Họ Tên: Nguyễn Lê Thanh Cường  
                  Năm sinh: 18/07/2004  
                  SĐT: 0902677204  
                  Email: nguyenlethanhcuong@gmail.com  

  education:
    title: Học vấn
    icon: fas fa-graduation-cap
    list:
      - degree: Sinh viên đại học
        college: Trường đại học Hutech
        dates: 2022 - 2026
        thesis_title: ""
        thesis_url: "#"
      - degree: Học sinh THPT
        college: Trường THPT Nguyễn Thị Diệu
        dates: 2019 - 2021
        thesis_title: ""
        thesis_url: "#"
      - degree: Học sinh THCS
        college: Trường THCS Đoàn Thị Điểm
        dates: 2015 - 2018
      - degree: Học sinh tiểu học
        college: Trường tiểu học Trương Quyền
        dates: 2010 - 2014
        thesis_title: ""
        thesis_url: "#" 
  project:
    title: Chứng chỉ chuyên môn
    icon: fas fa-project-diagram
    list:
      - title: Chứng chỉ Networking Basic
        url: "https://www.credly.com/badges/efb25927-c17e-41c7-af2b-a2f7e018220a"
        description: |
                      Nội dung: Hiểu biết cơ bản về mô hình mạng máy tính, thiết bị mạng (router, switch), địa chỉ IP và nguyên lý truyền dữ liệu.   
                      Kỹ năng đạt được: Thiết lập và cấu hình mạng LAN đơn giản, phân tích sự cố kết nối mạng cơ bản.
      - title: Chứng chỉ JavaScript Essentials 1
        url: "https://www.credly.com/badges/d054cfd9-74ba-4a81-bc91-e922027acd19"
        description: |
                      Nội dung: Hiểu cú pháp cơ bản của JavaScript, biến, hàm, điều kiện, vòng lặp và thao tác với DOM.  
                      Kỹ năng đạt được: Viết và chạy các chương trình JavaScript đơn giản, xử lý tương tác trên trang web, và tư duy lập trình hướng logic.
      - title: Chứng chỉ JavaScript Essentials 2
        url: "https://www.credly.com/badges/865ff216-cbf4-47be-84e7-e0c7561e0232"
        description: |
                      Nội dung: Kiến thức nâng cao về JavaScript bao gồm lập trình hướng đối tượng, xử lý lỗi, mô-đun, promise và lập trình bất đồng bộ.  
                      Kỹ năng đạt được: Viết ứng dụng JavaScript có cấu trúc tốt, quản lý luồng dữ liệu bất đồng bộ, và áp dụng nguyên tắc OOP trong phát triển web.
      
  skill:
    title: Kĩ năng mềm
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "Làm việc nhóm, quản lý thời gian"
        skillrating: 90
      - skill: Tư duy và phân tích
        skillrating: 80
      - skill: Giao tiếp
        skillrating: 60
  hobby:
    title: Sở thích
    icon: fas fa-gamepad
    list:
      - hobby: Bóng đá
      - hobby: Đọc sách
      - hobby: Nấu ăn
